# Generated by Django 5.0.2 on 2024-03-02 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('book', '0002_remove_bookorder_user_remove_feedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteauthor',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.author'),
            preserve_default=False,
        ),
    ]
