# Generated by Django 5.0.2 on 2024-03-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_favoriteauthor_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteAuthor',
        ),
    ]
