# Generated by Django 5.0.2 on 2024-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_favoriteauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
