# Generated by Django 5.0.2 on 2024-03-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_favoriteauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteauthor',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='book.author'),
        ),
    ]
