# Generated by Django 5.0.2 on 2024-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_favoriteauthor_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteauthor',
            name='author',
        ),
        migrations.AddField(
            model_name='favoriteauthor',
            name='author',
            field=models.ManyToManyField(blank=True, to='book.author'),
        ),
    ]
